// <auto-generated />
using System;
using AnahiQuezadaBurgerTarea.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnahiQuezadaBurgerTarea.Migrations
{
    [DbContext(typeof(AnahiQuezadaBurgerTareaContext))]
    [Migration("20240603012055_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnahiQuezadaBurgerTarea.Models.AQBurger", b =>
                {
                    b.Property<int>("AQBurgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AQBurgerId"));

                    b.Property<string>("AQName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AQPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("AQWithCheese")
                        .HasColumnType("bit");

                    b.HasKey("AQBurgerId");

                    b.ToTable("AQBurger");
                });

            modelBuilder.Entity("AnahiQuezadaBurgerTarea.Models.AQPromo", b =>
                {
                    b.Property<int>("AQPromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AQPromoId"));

                    b.Property<int>("AQBurgerId")
                        .HasColumnType("int");

                    b.Property<string>("AQDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AQFechaPromo")
                        .HasColumnType("datetime2");

                    b.HasKey("AQPromoId");

                    b.HasIndex("AQBurgerId");

                    b.ToTable("AQPromo");
                });

            modelBuilder.Entity("AnahiQuezadaBurgerTarea.Models.AQPromo", b =>
                {
                    b.HasOne("AnahiQuezadaBurgerTarea.Models.AQBurger", "AQBurger")
                        .WithMany("AQPromo")
                        .HasForeignKey("AQBurgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AQBurger");
                });

            modelBuilder.Entity("AnahiQuezadaBurgerTarea.Models.AQBurger", b =>
                {
                    b.Navigation("AQPromo");
                });
#pragma warning restore 612, 618
        }
    }
}
